title: "Your Project Title"
description: "Introduction to Machine Learning for Economists (Under Construction)"
theme: jekyll-theme-minimal
markdown: kramdown

# Plugins to enhance functionality
plugins:
  - jekyll-toc # for automatic table of contents

# Header and sidebar options
header:
  title: "Introduction to Machine Learning for Economists"
  logo: "logo.png" # Add a logo image if you have one

# Table of contents
toc:
  depth: 3
  label: "Table of contents"

# Navigation bar
navbar:
  - text: "Welcome"
    url: "/welcome"
  - text: "Basics"
    children:
      - text: "Non-linear function estimation"
        url: "/non-linear-function-estimation"
      - text: "Bias-variance Trade-off"
        url: "/bias-variance-tradeoff"
      - text: "Cross-validation"
        url: "/cross-validation"
      - text: "Regression Shrinkage Methods"
        url: "/regression-shrinkage-methods"
      - text: "Bootstrap"
        url: "/bootstrap"
  - text: "Prediction ML"
    children:
      - text: "Random Forest"
        url: "/random-forest"
      - text: "Boosted Regression Forest"
        url: "/boosted-regression-forest"
      - text: "Extreme Gradient Boosting"
        url: "/extreme-gradient-boosting"
