project:
  type: website
  output-dir: docs

website:
  title: "Jaeseok Hwang"
  site-url: https://jaeseokh.github.io/
  description: "Ph.D. candidate in Applied Economics (Estimated Graduation in May 2025)"
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    right:
    - text: "Home"
      href: index.qmd
    - text: "Resume"
      href: Resume.qmd  # Simplified name
      icon: user-cog
    - text: "Research"
      href: research/index.qmd
      icon: flask
    - text: "Essays"
      href: essays/index.qmd
      icon: pen-to-square

format:
  html:
    theme: cosmo
    css: styles.scss
    mainfont: sans-serif
    fontsize: 20px
    page-layout: full
    toc: true
    toc-depth: 2
    # Ensure Font Awesome is included
    include-in-header: |
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">