project:
  type: website
  output-dir: docs

website:
  title: "Jaeseok Hwang"
  site-url: https://jaeseokh.github.io/
  description: "Ph.D. candidate in Applied Economics (Estimated Graduation in May 2025)"
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    right:
    - text: "Home"
      href: index.qmd
    - text: "CV"
      href: cv.qmd
    - text: "Projects"
      href: projects/index.qmd
    - text: "Publications"
      href: publications/index.qmd
    - text: "Contact"
      href: contact.qmd


format:
  html:
    theme: cosmo  # Replace 'solana' with 'cosmo' or another theme of your choice
    css: styles.scss  # Custom CSS file for further styling
    toc: true
    toc-depth: 2

# Customize author details
author:
  name: "Jaeseok Hwang"
  image: headshot.jpg
  image-shape: "default"  # Use "default" to keep the rectangular shape
  description: "Ph.D. candidate in Applied Economics (Expected Graduation in May 2025)"
  links:
    - icon: github
      text: "GitHub"
      href: "https://github.com/jaeseokh"
    - icon: linkedin
      text: "LinkedIn"
      href: "https://www.linkedin.com/in/hwang-jaeseok-15ab94171/"
    - icon: envelope-fill
      text: "Email"
      href: "mailto:jaeseok2@illinois.edu"
