project:
  type: website
  output-dir: docs

website:
  title: "Jaeseok Hwang"
  site-url: https://jaeseokh.github.io/
  description: "Ph.D. candidate in Applied Economics (Estimated Graduation in May 2025)"
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    right:
    - text: "Home"
      href: index.qmd
    - text: "Resume"
      href: Resume.qmd  # Simplified name
      icon: person-gear
    - text: "Research"
      href: research/index.qmd
      icon: flask
    - text: "Essays"
      href: essays/index.qmd
      icon: pen-to-square

format:
  html:
    theme: cosmo  # Specify the theme here
    css: styles.scss  # Custom CSS file for further styling
    mainfont: sans-serif
    fontsize: 20px
    page-layout : full
    toc: true
    toc-depth: 2
